[project]
name = "coinbase-agentkit"
version = "0.6.0"
description = "Coinbase AgentKit"
authors = [{ name = "John Peterson", email = "john.peterson@coinbase.com" }]
requires-python = "~=3.10"
readme = "README.md"
license = "Apache-2.0"
keywords = [
    "coinbase",
    "sdk",
    "crypto",
    "cdp",
    "agentkit",
    "ai",
    "agent",
]
dependencies = [
    "cdp-sdk>=1.6.1,<2",
    "pydantic~=2.0",
    "web3>=7.6.0,<8",
    "python-dotenv>=1.0.1,<2",
    "requests>=2.31.0,<3",
    "allora-sdk>=0.2.0,<0.3",
    "paramiko>=3.5.1,<4",
    "nilql>=0.0.0a12,<0.0.1",
    "ecdsa>=0.19.0,<0.20",
    "pyjwt[crypto]>=2.10.1,<3",
    "jsonschema>=4.23.0,<5",
]

[tool.hatch.metadata]
allow-direct-references = true

[project.scripts]
check-description-length = "scripts.check_description_length:main"
generate-action-provider = "scripts.generate_action_provider.main:main"

[dependency-groups]
dev = [
    "ruff>=0.7.1,<0.8",
    "mypy>=1.13.0,<2",
    "pytest>=8.3.3,<9",
    "pytest-cov>=6.0.0,<7",
    "sphinx>=8.0.2,<9",
    "sphinx-autobuild>=2024.9.19,<2025",
    "sphinxcontrib-napoleon>=0.7,<0.8",
    "sphinx-autodoc-typehints>=2.4.4,<3",
    "myst-parser>=4.0.0,<5",
    "ruff-lsp>=0.0.58,<0.0.59",
    "python-lsp-server>=1.12.0,<2",
    "tweepy>=4.15.0,<5",
    "towncrier>=24.8.0,<25",
    "jinja2>=3.1.3,<4",
    "typer>=0.9.0,<0.10",
    "prompt-toolkit>=3.0.50,<4",
    "questionary>=2.1.0,<3",
    "rich>=13.7.1,<14",
    "pillow>=11.1.0,<12",
]

[tool.hatch.build.targets.sdist]
include = ["coinbase_agentkit"]

[tool.hatch.build.targets.wheel]
include = ["coinbase_agentkit"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.mypy]
python_version = "3.10"
strict = true
ignore_missing_imports = true

[tool.ruff]
line-length = 100
target-version = "py310"
exclude = ["./build/**", "./dist/**", "./docs/**"]

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W", "D", "UP", "B", "C4", "SIM", "RUF"]
ignore = ["D213", "D203", "D100", "D104", "D107", "E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.isort]
known-first-party = ["coinbase_agentkit, cdp"]
combine-as-imports = true

[tool.towncrier]
package = "coinbase_agentkit"
filename = "CHANGELOG.md"
directory = "changelog.d/"
title_format = "## [{version}] - {project_date}"
issue_format = "[#{issue}](https://github.com/coinbase/agentkit/pull/{issue})"

[tool.towncrier.fragment.feature]
name = "Added"

[tool.towncrier.fragment.bugfix]
name = "Fixed"

[tool.pytest.ini_options]
addopts = "-m 'not e2e'"
markers = [
    "e2e: marks tests as end-to-end tests that interact with real services",
    "manual: marks tests that should only be run manually (e.g., tests that incur costs)"
]
