[project]
name = "chatbot-python-with-nillion-secretvault"
version = "0.0.1"
description = "CDP AgentKit Example Chatbot"
authors = [
    { name = "John Peterson", email = "john.peterson@coinbase.com" },
    { name = "Niko Wehr", email = "nicholas.wehr@nillion.com" },
]
requires-python = "~=3.10"
readme = "README.md"
dependencies = [
    "python-dotenv>=1.0.1,<2",
    "langchain-openai>=0.2.4,<0.3",
    "langgraph>=0.2.39,<0.3",
    "coinbase-agentkit",
    "coinbase-agentkit-langchain",
]

[dependency-groups]
dev = ["ruff>=0.7.1,<0.8"]

[tool.uv]
package = false

[tool.uv.sources]
coinbase-agentkit = { path = "../../../python/coinbase-agentkit", editable = true }
coinbase-agentkit-langchain = { path = "../../../python/framework-extensions/langchain", editable = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.langchain-cdp-chatbot]
private = true

[tool.ruff]
line-length = 100
target-version = "py310"
exclude = ["./build/**", "./dist/**", "./docs/**"]

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W", "D", "UP", "B", "C4", "SIM", "RUF"]
ignore = ["D213", "D203", "D100", "D104", "D107", "E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.isort]
known-first-party = ["coinbase_agentkit, cdp"]
